# Function

In [22]:
import person
import nama
person.name

'zack'

In [20]:
person.devices

['laptop', 'smartphone', 'tablet']

In [21]:
person.display('hallo elita')

arg = hallo elita


In [23]:
nama.display('irfan')

namanya adalah irfan


## From

In [22]:
from person import name, devices
name

'zack'

In [23]:
devices

['laptop', 'smartphone', 'tablet']

In [26]:
from person import name as n, devices as d

In [25]:
n

'zack'

In [ ]:
import pandas
pd.read_csv('data.csv')

In [31]:
!pip install pandas


You should consider upgrading via the 'c:\users\dell\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [29]:
import pkg.mod1, pkg.mod2
pkg.mod1.color

'red'

In [30]:
from pkg.mod1 import color
color

'red'

In [14]:
import pkg.mod1, pkg.mod2
pkg.mod1.kitchen_sets

In [15]:
pkg.mod1.kitchen_sets

['fork', 'spoon', 'plate', 'knife']

In [16]:
import importlib
importlib.reload(pkg.mod1)

<module 'pkg.mod1' from 'c:\\Users\\Dell\\Documents\\Materi DTS\\complete_materi\\1_basic_python\\function_package\\pkg\\mod1.py'>

In [17]:
pkg.mod1.kitchen_sets

['fork', 'spoon', 'plate']

In [5]:
import sys
sys.path.append(r'C:\Users\Dell\Documents\Materi DTS\complete_materi\1_basic_python\function_package')

In [6]:
sys.path

['c:\\Users\\Dell\\Documents\\Materi DTS\\complete_materi\\1_basic_python\\function_package',
 'c:\\Users\\Dell\\.vscode\\extensions\\ms-toolsai.jupyter-2021.11.1001550889\\pythonFiles',
 'c:\\Users\\Dell\\.vscode\\extensions\\ms-toolsai.jupyter-2021.11.1001550889\\pythonFiles\\lib\\python',
 'C:\\Users\\Dell\\AppData\\Local\\Programs\\Python\\Python39\\python39.zip',
 'C:\\Users\\Dell\\AppData\\Local\\Programs\\Python\\Python39\\DLLs',
 'C:\\Users\\Dell\\AppData\\Local\\Programs\\Python\\Python39\\lib',
 'C:\\Users\\Dell\\AppData\\Local\\Programs\\Python\\Python39',
 '',
 'C:\\Users\\Dell\\AppData\\Roaming\\Python\\Python39\\site-packages',
 'C:\\Users\\Dell\\AppData\\Roaming\\Python\\Python39\\site-packages\\win32',
 'C:\\Users\\Dell\\AppData\\Roaming\\Python\\Python39\\site-packages\\win32\\lib',
 'C:\\Users\\Dell\\AppData\\Roaming\\Python\\Python39\\site-packages\\Pythonwin',
 'C:\\Users\\Dell\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages',
 'C:\\Users\\Dell\\AppD

In [8]:
import person
person.__file__

'c:\\Users\\Dell\\Documents\\Materi DTS\\complete_materi\\1_basic_python\\function_package\\person.py'

# Numpy

In [ ]:
!pip install numpy
!py -m pip install numpy

In [32]:
import numpy as np

In [33]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [34]:
np.zeros(3)

array([0., 0., 0.])

In [35]:
np.ones(2)

array([1., 1.])

In [41]:
np.empty(2)

array([1., 1.])

In [45]:
print(np.arange(2,11,3))
print(np.arange(2))

[2 5 8]
[0 1]


In [46]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight/height**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [47]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
np_height = np.array(height)
np_weight = np.array(weight)
np_weight/np_height**2

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [48]:
height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
weight/height**2

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [49]:
arr= np.array([1,2,3,4,5])
np.append(arr, [6,7,8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
arr= np.array([1,3,7,5])
print(np.append(arr, [6,7,8]))

[1 3 7 5 6 7 8]


In [54]:
np.delete(arr, 3)

array([1, 3, 7])

In [55]:
np.sort(arr)

array([1, 3, 5, 7])

In [67]:
import numpy as np
array_1 = np.array([[[1,2,3,4,5],
                    [6,7,8,9,10]],

                    [[11,12,13,14,15],
                    [16,17,18,19,20]],
                    
                    [[21,22,23,24,25],
                    [26,27,28,29,30]]])


print(array_1)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]


In [69]:
array_1.ndim

3

In [70]:
array_1.size

30

In [71]:
array_1.shape

(3, 2, 5)

In [68]:
scalar= np.array(32)
print(scalar) # 0D
print(scalar.ndim)

32
0


In [64]:
vektor= np.array([1,2,3,4]) #1D
print(vektor)

[1 2 3 4]


In [72]:
matriks= np.array([[1,2,3,4],
                     [5,6,7,8]]) #2D
print(matriks)
matriks.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [73]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [78]:
b = a.reshape(3,2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [79]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [80]:
# You can use np.newaxis to add a new axis:

a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[0 1 2 3 4 5]]


In [81]:
# You can convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[0 1 2 3 4 5]]


In [82]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [85]:
a

array([1, 2, 3, 4, 5, 6])

In [84]:
# You can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1)
print(b)
b.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

In [88]:
b.shape[1]

1

In [89]:
# You can add an axis at index position 0 with:

c = np.expand_dims(a, axis=0)
print(c)
c.shape

[[1 2 3 4 5 6]]


(1, 6)

In [90]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [91]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [92]:
# You can easily print all of the values in the array that are less than 5

print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [94]:
# You can select elements that are divisible by 2

divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 1  3  5  7  9 11]


In [95]:
a_1 = np.array([[1, 1],
                [2, 2]])

a_2 = np.array([[3, 3],
                [4, 4]])
                
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [96]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [97]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [100]:
# If you wanted to split this array into three equally shaped arrays

np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [101]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [102]:
# You can create a new array object that looks at the same data

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [103]:
# Using the copy method will make a complete copy of the array and its data (a deep copy).

c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [104]:
a = np.array([1, 2, 3, 4])

# Add all of the elements in the array
a.sum()

10

In [108]:
b = np.array([[2, 1], 
              [2, 2]])
b

array([[2, 1],
       [2, 2]])

In [111]:
b.shape

(2, 2)

In [109]:
# You can sum the rows

b.sum(axis=0)

array([4, 3])

In [110]:
b.sum(axis=1)

array([3, 4])

# Latihan

In [114]:
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)
print(x.shape)
print(x.ndim)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
(3, 3)
2


In [116]:
arr = np.array(70) 
print(arr)
arr.ndim

70


0

In [118]:
arr = np.array([[1, 2, 3], [4, 5, 6], [4, 5, 6]])
print(arr)
arr.shape

[[1 2 3]
 [4 5 6]
 [4 5 6]]


(3, 3)

In [120]:
arr = np.array([[[1, 2, 3], 
                [4, 5, 6]],
                 
                [[1, 2, 3], 
                [4, 5, 6]]])
print(arr)
arr.shape

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


(2, 2, 3)

In [122]:
array_tes = np.array([[3, 7, 10, 2], [3, 7, 10, 2]], ndmin=3)
print(array_tes)

[[[ 3  7 10  2]
  [ 3  7 10  2]]]


In [123]:
import numpy as np
array_tes = np.array([3, 10, 3, 2])

print(array_tes[3] + array_tes[2])

5


In [172]:
arr = np.array([[6,7,8,9,10],[1,2,3,4,5]])
print(arr[:3, :1])

[[6]
 [1]]


In [129]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], 
                [[7, 8, 9], [10, 11, 12]]])

print(arr[:, 1, 2])
print(arr.shape)

[ 6 12]
(2, 2, 3)


In [165]:
print(arr[:1, :2,:1])

[[[1]
  [4]]]


In [173]:
arr = np.array([[6,7,8,9,10],[1,2,3,4,5]])
print(arr[-1, -1])

5


In [175]:
arr = np.array([ 4, 5, 6, 7, 1, 2, 3])

print(arr[1:5:4])

[5]


In [179]:
arr = np.array([2, 2, 7, 4, 5, 6, 7,8,10])
print(arr[2:8:3]) # START, END, STEP
print(arr[:2])

[7 6]
[2 2]


In [182]:
arr= np.array([1,2,3,4])
arr.shape

(4,)

In [181]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:1, 1:3])

[[2 3]]


In [188]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9,10,11,12])
newarr = arr.reshape(1, 2, -1)
print(newarr, "\n")
print(newarr.shape)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]] 

(1, 2, 6)
