In [1]:
import person

In [2]:
person.name

'zack'

# From

In [7]:
from person import name, devices, display
name

'zack'

In [5]:
devices

['laptop', 'smartphone', 'tablet']

In [8]:
display

<function person.display(arg)>

In [1]:
!pip install pandas

You should consider upgrading via the 'C:\Users\rezal\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


# numpy

In [13]:
import numpy as np

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.ones(2)

array([1., 1.])

In [24]:
print(np.arange(2,11,2))
print(np.arange(2))


[ 2  4  6  8 10]
[0 1]


In [25]:
tinggi=np.array([1.73, 1.68, 1.71, 1.89, 1.79])
berat=np.array([64.5, 59.2, 60.8, 70.1, 67.5])
berat/tinggi**2

array([21.55100404, 20.97505669, 20.79272255, 19.62431063, 21.06675822])

In [26]:
arr=np.array([1,2,3,4,5])
np.append(arr,[6,7,8,9,10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
tinggi=np.array([1.73, 1.68, 1.71, 1.89, 1.79])
berat=np.array([64.5, 59.2, 60.8, 70.1, 67.5])
rata=berat*tinggi/2

print(rata)

[55.7925 49.728  51.984  66.2445 60.4125]


In [29]:
np.delete(arr,3)

array([1, 2, 3, 5])

In [47]:
array_1=np.array([[[1,2,3,4,5],
                [6,7,8,9,10]],

                [[11,12,13,14,15],
                [16,17,18,19,20]]])
print(array_1)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [56]:
array_1.ndim #dimensi liat kurung []

3

In [57]:
array_1.size

20

In [58]:
array_1.shape

(2, 2, 5)

In [14]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [20]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


# Latihan

In [28]:
x=np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [30]:
arr=np.array(70)
print(arr)
print(arr.ndim)

70
0


In [32]:
arr=np.array([[1,2,3],[5,6,7],[8,9,10]])
print(arr)
arr.shape

[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]


(3, 3)

In [53]:
arr=np.array([[[1,2,3,4,],
                [6,7,8,9,]],

                [[11,12,13,14,],
                [16,17,18,19]]])
print(arr)

[[[ 1  2  3  4]
  [ 6  7  8  9]]

 [[11 12 13 14]
  [16 17 18 19]]]


In [55]:
arr=np.array([4,5,6,7,1,2,3])
print(arr[1:5:4])

[5]


In [57]:
arr=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
